import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<string, Record<Language, string>> = {
  // Navigation
  'nav.home': { en: 'Home', ta: 'முகப்பு' },
  'nav.about': { en: 'About Us', ta: 'எங்களை பற்றி' },
  'nav.departments': { en: 'Departments', ta: 'துறைகள்' },
  'nav.doctors': { en: 'Doctors', ta: 'மருத்துவர்கள்' },
  'nav.services': { en: 'Services', ta: 'சேவைகள்' },
  'nav.contact': { en: 'Contact', ta: 'தொடர்பு' },
  'nav.login': { en: 'Login', ta: 'உள்நுழை' },
  'nav.dashboard': { en: 'Dashboard', ta: 'கட்டுப்பாட்டு பலகை' },

  // Home Page
  'hero.title': { en: 'Excellence in Healthcare', ta: 'சிறந்த மருத்துவ சேவை' },
  'hero.subtitle': { en: 'Providing compassionate, quality healthcare for you and your family', ta: 'உங்களுக்கும் உங்கள் குடும்பத்திற்கும் கருணையான, தரமான மருத்துவ சேவை வழங்குகிறோம்' },
  'hero.bookAppointment': { en: 'Book Appointment', ta: 'சந்திப்பு பதிவு செய்' },
  'hero.emergency': { en: 'Emergency', ta: 'அவசரம்' },
  'hero.viewDepartments': { en: 'View Departments', ta: 'துறைகளை பார்க்க' },
  'home.stats.experience': { en: 'Years Experience', ta: 'ஆண்டுகள் அனுபவம்' },
  'home.about.extra': { en: 'With state-of-the-art medical equipment, experienced healthcare professionals, and a patient-first approach, we ensure the highest standards of medical care for every individual who walks through our doors.', ta: 'நவீன மருத்துவ உபகரணங்கள், அனுபவமிக்க மருத்துவ பணியாளர்கள் மற்றும் நோயாளி முதன்மை அணுகுமுறை ஆகியவற்றுடன், எங்கள் மருத்துவமனைக்கு வரும் ஒவ்வொருவருக்கும் உயர்ந்த தரத்தில் மருத்துவ சேவை வழங்குவதை உறுதிப்படுத்துகிறோம்.' },
  'home.cta.title': { en: 'Ready to Get Started?', ta: 'தொடங்கத் தயாரா?' },
  'home.cta.subtitle': { en: 'Book your appointment today and experience quality healthcare', ta: 'இன்றே உங்கள் சந்திப்பை பதிவு செய்து தரமான மருத்துவ சேவையை அனுபவிக்கவும்' },

  // About Section
  'about.title': { en: 'About Our Hospital', ta: 'எங்கள் மருத்துவமனை பற்றி' },
  'about.description': { en: 'Dedicated to providing exceptional healthcare services with state-of-the-art facilities and experienced medical professionals.', ta: 'நவீன வசதிகள் மற்றும் அனுபவமிக்க மருத்துவ நிபுணர்களுடன் சிறந்த மருத்துவ சேவைகளை வழங்குவதில் அர்ப்பணிப்பு.' },
  'about.learnMore': { en: 'Learn More', ta: 'மேலும் அறிய' },
  'about.mission.title': { en: 'Our Mission', ta: 'எங்கள் பணி' },
  'about.mission.description': { en: 'To provide accessible, affordable, and quality healthcare services to our community. We strive to promote wellness, prevent illness, and restore health through compassionate care and medical excellence.', ta: 'எங்கள் சமூகத்திற்கு எளிதில் அணுகக்கூடிய, மலிவான மற்றும் உயர்தர மருத்துவச் சேவைகளை வழங்குவது. கருணையுடனும் மருத்துவ மேன்மையுடனும் நலத்தை மேம்படுத்தவும், நோயைத் தடுக்கவும், ஆரோக்கியத்தை மீட்டெடுக்கவும் நாம் முயல்கிறோம்.' },
  'about.vision.title': { en: 'Our Vision', ta: 'எங்கள் நோக்கம்' },
  'about.vision.description': { en: 'To be the leading healthcare provider recognized for clinical excellence, innovative treatments, and patient satisfaction. We envision a healthier community where everyone has access to world-class medical care.', ta: 'மருத்துவ மேன்மை, புதுமையான சிகிச்சைகள் மற்றும் நோயாளி திருப்திநிலைக்கு அங்கீகரிக்கப்படும் முன்னணி மருத்துவ சேவை வழங்குநராக இருப்பது. உலகத் தரத்திலான மருத்துவ சேவை அனைவருக்கும் கிடைக்கும் ஆரோக்கியமான சமூகத்தை நாங்கள் நோக்கமாகக் கொண்டுள்ளோம்.' },
  'about.values.sectionTitle': { en: 'Our Core Values', ta: 'எங்கள் அடிப்படை மதிப்புகள்' },
  'about.values.sectionSubtitle': { en: 'The principles that guide everything we do', ta: 'நாம் செய்யும் ஒவ்வொரு செயலையும் வழிநடத்தும் கோட்பாடுகள்' },
  'about.values.compassion.title': { en: 'Compassionate Care', ta: 'கருணைமிக்க பராமரிப்பு' },
  'about.values.compassion.desc': { en: 'We treat every patient with empathy, respect, and kindness', ta: 'ஒவ்வொரு நோயாளியையும் கருணை, மரியாதை மற்றும் அன்புடன் நடத்துகிறோம்' },
  'about.values.excellence.title': { en: 'Excellence', ta: 'மேன்மை' },
  'about.values.excellence.desc': { en: 'Committed to the highest standards of medical care', ta: 'உயர்தர மருத்துவச் சேவைக்கு அர்ப்பணிப்பு' },
  'about.values.patient.title': { en: 'Patient-Centered', ta: 'நோயாளி மையப்படுத்தப்பட்ட' },
  'about.values.patient.desc': { en: 'Your health and wellbeing are our top priorities', ta: 'உங்கள் ஆரோக்கியமும் நலனும் எங்கள் முதன்மை கவனமாகும்' },
  'about.values.professional.title': { en: 'Professional', ta: 'தொழில்முறை' },
  'about.values.professional.desc': { en: 'Expert medical team with years of experience', ta: 'பல ஆண்டுகள் அனுபவமுள்ள நிபுணர் மருத்துவக் குழு' },
  'about.achievements.title': { en: 'Accreditation & Achievements', ta: 'அங்கீகாரங்கள் மற்றும் சாதனைகள்' },
  'about.achievements.established': { en: 'Hospital Established', ta: 'மருத்துவமனை நிறுவப்பட்டது' },
  'about.achievements.nabh': { en: 'NABH Accredited', ta: 'NABH அங்கீகாரம் பெற்றது' },
  'about.achievements.iso': { en: 'ISO 9001:2015 Certified', ta: 'ISO 9001:2015 சான்றளிக்கப்பட்டது' },
  'about.achievements.green': { en: 'Green Hospital Recognition', ta: 'பசுமை மருத்துவமனை அங்கீகாரம்' },
  'about.achievements.covid': { en: 'COVID Care Excellence Award', ta: 'கோவிட் பராமரிப்பு மேன்மை விருது' },
  'about.achievements.multiSpecialty': { en: 'Best Multi-Specialty Hospital', ta: 'சிறந்த பல்துறை மருத்துவமனை' },

  // Services
  'services.title': { en: 'Our Services', ta: 'எங்கள் சேவைகள்' },
  'services.emergency': { en: '24/7 Emergency Care', ta: '24/7 அவசர சேவை' },
  'services.emergencyDesc': { en: 'Round-the-clock emergency medical services', ta: 'நாள் முழுவதும் அவசர மருத்துவ சேவைகள்' },
  'services.specialist': { en: 'Specialist Consultations', ta: 'சிறப்பு ஆலோசனை' },
  'services.specialistDesc': { en: 'Expert doctors across multiple specialties', ta: 'பல சிறப்புகளில் நிபுணர் மருத்துவர்கள்' },
  'services.diagnostic': { en: 'Advanced Diagnostics', ta: 'மேம்பட்ட கண்டறிதல்' },
  'services.diagnosticDesc': { en: 'State-of-the-art diagnostic facilities', ta: 'நவீன கண்டறிதல் வசதிகள்' },
  'services.pharmacy': { en: 'Pharmacy Services', ta: 'மருந்தக சேவைகள்' },
  'services.pharmacyDesc': { en: 'In-house pharmacy with quality medicines', ta: 'தரமான மருந்துகளுடன் உள் மருந்தகம்' },
  'services.subtitle': { en: 'Comprehensive healthcare services designed to meet all your medical needs', ta: 'உங்கள் அனைத்து மருத்துவத் தேவைகளையும் பூர்த்தி செய்ய உருவாக்கப்பட்ட விரிவான மருத்துவ சேவைகள்' },
  'services.packages.title': { en: 'Health Checkup Packages', ta: 'சுகாதார பரிசோதனை திட்டங்கள்' },
  'services.packages.description': { en: 'Comprehensive health screening programs', ta: 'விரிவான சுகாதார பரிசோதனை திட்டங்கள்' },
  'services.insurance.title': { en: 'Insurance Services', ta: 'காப்பீட்டு சேவைகள்' },
  'services.insurance.description': { en: 'Cashless treatment facility', ta: 'பணமில்லா சிகிச்சை வசதி' },
  'services.preventive.title': { en: 'Preventive Care', ta: 'தடுப்பு பராமரிப்பு' },
  'services.preventive.description': { en: 'Health education and wellness programs', ta: 'சுகாதார கல்வியும் நலத் திட்டங்களும்' },
  'services.maternity.title': { en: 'Maternity Care', ta: 'கர்ப்ப பராமரிப்பு' },
  'services.maternity.description': { en: 'Complete care for mother and baby', ta: 'தாய் மற்றும் குழந்தைக்கு முழுமையான பராமரிப்பு' },
  'services.features.emergency.trauma': { en: 'Trauma care unit', ta: 'அவசர காயப் பராமரிப்பு பிரிவு' },
  'services.features.emergency.critical': { en: 'Critical care services', ta: 'முக்கிய பராமரிப்பு சேவைகள்' },
  'services.features.emergency.surgery': { en: 'Emergency surgery', ta: 'அவசர அறுவை சிகிச்சை' },
  'services.features.emergency.ambulance': { en: 'Ambulance services', ta: 'ஆம்புலன்ஸ் சேவைகள்' },
  'services.features.specialist.multi': { en: 'Multi-specialty consultations', ta: 'பல்துறை ஆலோசனைகள்' },
  'services.features.specialist.second': { en: 'Second opinion services', ta: 'இரண்டாவது கருத்து சேவைகள்' },
  'services.features.specialist.followup': { en: 'Follow-up care', ta: 'பின்தொடர்பு பராமரிப்பு' },
  'services.features.specialist.telemedicine': { en: 'Telemedicine available', ta: 'தொலைமருத்துவ சேவை கிடைக்கும்' },
  'services.features.diagnostic.xray': { en: 'Digital X-Ray', ta: 'டிஜிட்டல் எக்ஸ்-ரே' },
  'services.features.diagnostic.ct': { en: 'CT & MRI scans', ta: 'சிடி மற்றும் எம்ஆர்ஐ ஸ்கான்' },
  'services.features.diagnostic.lab': { en: 'Laboratory services', ta: 'ஆய்வக சேவைகள்' },
  'services.features.diagnostic.pathology': { en: 'Pathology testing', ta: 'பாதாலஜி பரிசோதனை' },
  'services.features.pharmacy.roundClock': { en: '24/7 pharmacy services', ta: '24/7 மருந்தகம் சேவைகள்' },
  'services.features.pharmacy.delivery': { en: 'Home delivery available', ta: 'வீட்டிற்கு வழங்கும் சேவை கிடைக்கும்' },
  'services.features.pharmacy.generic': { en: 'Generic medicines', ta: 'பொதுவான மருந்துகள்' },
  'services.features.pharmacy.counseling': { en: 'Medicine counseling', ta: 'மருந்து ஆலோசனை' },
  'services.features.packages.executive': { en: 'Executive health checkup', ta: 'நிர்வாக சுகாதார பரிசோதனை' },
  'services.features.packages.cardiac': { en: 'Cardiac screening', ta: 'இதய பரிசோதனை' },
  'services.features.packages.diabetes': { en: 'Diabetes screening', ta: 'சர்க்கரை நோய் பரிசோதனை' },
  'services.features.packages.cancer': { en: 'Cancer screening', ta: 'புற்றுநோய் பரிசோதனை' },
  'services.features.insurance.accepted': { en: 'All major insurance accepted', ta: 'முக்கிய காப்பீட்டு திட்டங்கள் அனைத்தும் ஏற்கப்படுகின்றன' },
  'services.features.insurance.cashless': { en: 'Cashless facility', ta: 'பணமில்லா வசதி' },
  'services.features.insurance.claims': { en: 'Claim assistance', ta: 'கோரிக்கை உதவி' },
  'services.features.insurance.corporate': { en: 'Corporate tie-ups', ta: 'நிறுவன ஒப்பந்தங்கள்' },
  'services.features.preventive.vaccination': { en: 'Vaccination programs', ta: 'தடுப்பூசி திட்டங்கள்' },
  'services.features.preventive.education': { en: 'Health education', ta: 'சுகாதார கல்வி' },
  'services.features.preventive.nutrition': { en: 'Nutrition counseling', ta: 'உணவியல் ஆலோசனை' },
  'services.features.preventive.fitness': { en: 'Fitness programs', ta: 'உடற்பயிற்சி திட்டங்கள்' },
  'services.features.maternity.antenatal': { en: 'Antenatal care', ta: 'கர்ப்ப கால பராமரிப்பு' },
  'services.features.maternity.labor': { en: 'Labor & delivery', ta: 'பிரசவமும் குழந்தைப் பிறப்பும்' },
  'services.features.maternity.postnatal': { en: 'Postnatal care', ta: 'பிற்பிறப்பு பராமரிப்பு' },
  'services.features.maternity.lactation': { en: 'Lactation support', ta: 'இருத்தல் ஆதரவு' },
  'services.cta.title': { en: 'Need Medical Assistance?', ta: 'மருத்துவ உதவி தேவைப்படுகிறதா?' },
  'services.cta.subtitle': { en: 'Our team is available 24/7 to help you', ta: 'உங்களுக்கு உதவ எங்கள் குழு 24/7 தயாராக உள்ளது' },

  // Departments
  'departments.title': { en: 'Our Departments', ta: 'எங்கள் துறைகள்' },
  'departments.cardiology': { en: 'Cardiology', ta: 'இருதய மருத்துவம்' },
  'departments.cardiologyDesc': { en: 'Heart and cardiovascular care', ta: 'இதய மற்றும் இதய நாள மருத்துவம்' },
  'departments.orthopedics': { en: 'Orthopedics', ta: 'எலும்பியல்' },
  'departments.orthopedicsDesc': { en: 'Bone and joint specialists', ta: 'எலும்பு மற்றும் மூட்டு நிபுணர்கள்' },
  'departments.pediatrics': { en: 'Pediatrics', ta: 'குழந்தை மருத்துவம்' },
  'departments.pediatricsDesc': { en: 'Specialized care for children', ta: 'குழந்தைகளுக்கான சிறப்பு பராமரிப்பு' },
  'departments.neurology': { en: 'Neurology', ta: 'நரம்பியல்' },
  'departments.neurologyDesc': { en: 'Brain and nervous system care', ta: 'மூளை மற்றும் நரம்பு மண்டல மருத்துவம்' },
  'departments.subtitle': { en: 'Comprehensive medical specialties under one roof', ta: 'ஒரே இடத்தில் விரிவான மருத்துவப் பிரிவுகள்' },
  'departments.ophthalmology': { en: 'Ophthalmology', ta: 'கண் மருத்துவம்' },
  'departments.ophthalmologyDesc': { en: 'Eye care and vision specialists', ta: 'கண் பராமரிப்பு மற்றும் பார்வை நிபுணர்கள்' },
  'departments.oncology': { en: 'Oncology', ta: 'புற்றுநோய் மருத்துவம்' },
  'departments.oncologyDesc': { en: 'Cancer diagnosis and treatment', ta: 'புற்றுநோய் கண்டறிதல் மற்றும் சிகிச்சை' },
  'departments.generalMedicine': { en: 'General Medicine', ta: 'பொது மருத்துவம்' },
  'departments.generalMedicineDesc': { en: 'Primary care and internal medicine', ta: 'அடிப்படை பராமரிப்பு மற்றும் உட்புற மருத்துவம்' },
  'departments.emergencyMedicine': { en: 'Emergency Medicine', ta: 'அவசர மருத்துவம்' },
  'departments.emergencyMedicineDesc': { en: '24/7 emergency care services', ta: '24/7 அவசர மருத்துவ சேவைகள்' },
  'departments.gastroenterology': { en: 'Gastroenterology', ta: 'செரிமான மருத்துவம்' },
  'departments.gastroenterologyDesc': { en: 'Digestive system specialists', ta: 'செரிமான மண்டல நிபுணர்கள்' },
  'departments.obgyn': { en: 'Obstetrics & Gynecology', ta: 'கர்ப்பம் மற்றும் மகளிர் மருத்துவம்' },
  'departments.obgynDesc': { en: "Women's health specialists", ta: 'பெண்களின் சுகாதார நிபுணர்கள்' },
  'departments.radiology': { en: 'Radiology', ta: 'கதிரியக்க மருத்துவம்' },
  'departments.radiologyDesc': { en: 'Advanced imaging and diagnostics', ta: 'மேம்பட்ட படமெடுப்பு மற்றும் கண்டறிதல்' },
  'departments.generalSurgery': { en: 'General Surgery', ta: 'பொது அறுவை சிகிச்சை' },
  'departments.generalSurgeryDesc': { en: 'Surgical procedures and operations', ta: 'அறுவை சிகிச்சை நடவடிக்கைகள் மற்றும் செயல்முறைகள்' },
  'departments.servicesLabel': { en: 'Services:', ta: 'சேவைகள்:' },
  'departments.doctorCount': { en: 'Doctors', ta: 'மருத்துவர்கள்' },
  'departments.button.viewDoctors': { en: 'View Doctors', ta: 'மருத்துவர்களைப் பார்க்க' },
  'departments.services.cardiology.ecg': { en: 'ECG', ta: 'ஈசிஜி' },
  'departments.services.cardiology.echo': { en: 'Echocardiography', ta: 'எகோகார்டியோகிராஃபி' },
  'departments.services.cardiology.angiography': { en: 'Angiography', ta: 'ஆன்ஜியோகிராஃபி' },
  'departments.services.cardiology.surgery': { en: 'Cardiac Surgery', ta: 'இதய அறுவை சிகிச்சை' },
  'departments.services.orthopedics.joint': { en: 'Joint Replacement', ta: 'மூட்டு மாற்று அறுவை சிகிச்சை' },
  'departments.services.orthopedics.fracture': { en: 'Fracture Care', ta: 'எலும்பு முறிவு பராமரிப்பு' },
  'departments.services.orthopedics.sports': { en: 'Sports Medicine', ta: 'விளையாட்டு மருத்துவம்' },
  'departments.services.orthopedics.spine': { en: 'Spine Surgery', ta: 'முதுகுத் தண்டு அறுவை சிகிச்சை' },
  'departments.services.pediatrics.vaccination': { en: 'Vaccination', ta: 'தடுப்பூசி' },
  'departments.services.pediatrics.development': { en: 'Child Development', ta: 'குழந்தை வளர்ச்சி' },
  'departments.services.pediatrics.neonatal': { en: 'Neonatal Care', ta: 'புதிய பிறந்த குழந்தை பராமரிப்பு' },
  'departments.services.pediatrics.surgery': { en: 'Pediatric Surgery', ta: 'குழந்தை அறுவை சிகிச்சை' },
  'departments.services.neurology.stroke': { en: 'Stroke Care', ta: 'ஸ்ட்ரோக் பராமரிப்பு' },
  'departments.services.neurology.epilepsy': { en: 'Epilepsy Treatment', ta: 'எபிலப்சி சிகிச்சை' },
  'departments.services.neurology.surgery': { en: 'Brain Surgery', ta: 'மூளை அறுவை சிகிச்சை' },
  'departments.services.neurology.nerves': { en: 'Nerve Disorders', ta: 'நரம்பு கோளாறுகள்' },
  'departments.services.ophthalmology.cataract': { en: 'Cataract Surgery', ta: 'கண்பார்வை மங்கல் அறுவை சிகிச்சை' },
  'departments.services.ophthalmology.lasik': { en: 'LASIK', ta: 'லேசிக்' },
  'departments.services.ophthalmology.glaucoma': { en: 'Glaucoma Treatment', ta: 'கிளூகோமா சிகிச்சை' },
  'departments.services.ophthalmology.retina': { en: 'Retina Care', ta: 'ரெடினா பராமரிப்பு' },
  'departments.services.oncology.chemo': { en: 'Chemotherapy', ta: 'கீமோதெரபி' },
  'departments.services.oncology.radiation': { en: 'Radiation Therapy', ta: 'கதிர்வீச்சு சிகிச்சை' },
  'departments.services.oncology.surgery': { en: 'Surgical Oncology', ta: 'அறுவை புற்றுநோய் மருத்துவம்' },
  'departments.services.oncology.palliative': { en: 'Palliative Care', ta: 'வலி நிவாரண பராமரிப்பு' },
  'departments.services.generalMedicine.checkups': { en: 'Health Checkups', ta: 'சுகாதார பரிசோதனைகள்' },
  'departments.services.generalMedicine.chronic': { en: 'Chronic Disease Management', ta: 'நீண்டகால நோய் மேலாண்மை' },
  'departments.services.generalMedicine.preventive': { en: 'Preventive Care', ta: 'தடுப்பு பராமரிப்பு' },
  'departments.services.generalMedicine.consultation': { en: 'Consultation', ta: 'ஆலோசனை' },
  'departments.services.emergency.trauma': { en: 'Trauma Care', ta: 'அவசர காய பராமரிப்பு' },
  'departments.services.emergency.critical': { en: 'Critical Care', ta: 'முக்கிய பராமரிப்பு' },
  'departments.services.emergency.surgery': { en: 'Emergency Surgery', ta: 'அவசர அறுவை சிகிச்சை' },
  'departments.services.emergency.ambulance': { en: 'Ambulance Services', ta: 'ஆம்புலன்ஸ் சேவைகள்' },
  'departments.services.gastro.endoscopy': { en: 'Endoscopy', ta: 'எண்டோஸ்கோப்பி' },
  'departments.services.gastro.colonoscopy': { en: 'Colonoscopy', ta: 'கோலோனோஸ்கோப்பி' },
  'departments.services.gastro.liver': { en: 'Liver Care', ta: 'கல்லீரல் பராமரிப்பு' },
  'departments.services.gastro.ibd': { en: 'IBD Treatment', ta: 'IBD சிகிச்சை' },
  'departments.services.obgyn.maternity': { en: 'Maternity Care', ta: 'கர்ப்ப பராமரிப்பு' },
  'departments.services.obgyn.surgery': { en: 'Gynecological Surgery', ta: 'மகளிர் அறுவை சிகிச்சை' },
  'departments.services.obgyn.fertility': { en: 'Fertility Treatment', ta: 'வந்தைத் திறன் சிகிச்சை' },
  'departments.services.obgyn.prenatal': { en: 'Prenatal Care', ta: 'கருவுற்ற பராமரிப்பு' },
  'departments.services.radiology.xray': { en: 'X-Ray', ta: 'எக்ஸ்-ரே' },
  'departments.services.radiology.ct': { en: 'CT Scan', ta: 'சிடி ஸ்கேன்' },
  'departments.services.radiology.mri': { en: 'MRI', ta: 'எம்ஆர்ஐ' },
  'departments.services.radiology.ultrasound': { en: 'Ultrasound', ta: 'அல்ட்ராசவுண்ட்' },
  'departments.services.generalSurgery.laparoscopic': { en: 'Laparoscopic Surgery', ta: 'லேபரோஸ்கோப்பிக் அறுவை சிகிச்சை' },
  'departments.services.generalSurgery.hernia': { en: 'Hernia Repair', ta: 'மூட்டு திருத்தம்' },
  'departments.services.generalSurgery.appendix': { en: 'Appendectomy', ta: 'அப்பெண்டிக்ஸ் அகற்றம்' },
  'departments.services.generalSurgery.gallbladder': { en: 'Gallbladder Surgery', ta: 'பித்தப்பை அறுவை சிகிச்சை' },

  // Doctors
  'doctors.title': { en: 'Our Doctors', ta: 'எங்கள் மருத்துவர்கள்' },
  'doctors.search': { en: 'Search doctors...', ta: 'மருத்துவர்களை தேடு...' },
  'doctors.viewProfile': { en: 'View Profile', ta: 'சுயவிவரம் பார்க்க' },
  'doctors.bookAppointment': { en: 'Book Appointment', ta: 'சந்திப்பு பதிவு செய்' },
  'doctors.experience': { en: 'years experience', ta: 'வருட அனுபவம்' },
  'doctors.page.title': { en: 'Our Expert Medical Team', ta: 'எங்கள் நிபுணர் மருத்துவக் குழு' },
  'doctors.page.subtitle': { en: 'Meet our team of experienced and dedicated healthcare professionals across various specialties', ta: 'பல துறைகளில் அனுபவமும் அர்ப்பணிப்பும் கொண்ட மருத்துவ நிபுணர்களை சந்தியுங்கள்' },
  'doctors.search.placeholder': { en: 'Search by name, department, or qualification...', ta: 'பெயர், துறை அல்லது தகுதி மூலம் தேடுங்கள்...' },
  'doctors.filter.placeholder': { en: 'Filter by Department', ta: 'துறையின்படி வடிகட்டு' },
  'doctors.filter.all': { en: 'All Departments', ta: 'அனைத்து துறைகளும்' },
  'doctors.button.viewDetails': { en: 'View Details', ta: 'விவரங்களை பார்க்க' },
  'doctors.empty.title': { en: 'No doctors available', ta: 'மருத்துவர்கள் இல்லை' },
  'doctors.empty.search': { en: 'No doctors found matching your search.', ta: 'உங்கள் தேடலுக்கு பொருந்தும் மருத்துவர்கள் எவரும் இல்லை.' },
  'doctors.empty.department': { en: 'No doctors available in this department.', ta: 'இந்த துறையில் மருத்துவர்கள் இல்லை.' },
  'doctors.button.viewAll': { en: 'View All Departments', ta: 'அனைத்து துறைகளையும் காண' },
  'doctors.ratingLabel': { en: 'Rating', ta: 'மதிப்பீடு' },
  'doctors.result.count': { en: 'Showing {count} doctors', ta: '{count} மருத்துவர்கள் காணப்படுகின்றனர்' },
  'doctors.result.department': { en: 'in {department}', ta: '{department} துறையில்' },
  'doctors.result.all': { en: 'across all departments', ta: 'அனைத்து துறைகளிலும்' },

  // Appointment
  'appointment.title': { en: 'Book an Appointment', ta: 'சந்திப்பு பதிவு செய்யுங்கள்' },
  'appointment.name': { en: 'Full Name', ta: 'முழு பெயர்' },
  'appointment.email': { en: 'Email', ta: 'மின்னஞ்சல்' },
  'appointment.phone': { en: 'Phone Number', ta: 'தொலைபேசி எண்' },
  'appointment.department': { en: 'Select Department', ta: 'துறையை தேர்வு செய்' },
  'appointment.doctor': { en: 'Select Doctor', ta: 'மருத்துவரை தேர்வு செய்' },
  'appointment.date': { en: 'Appointment Date', ta: 'சந்திப்பு தேதி' },
  'appointment.time': { en: 'Appointment Time', ta: 'சந்திப்பு நேரம்' },
  'appointment.message': { en: 'Message (Optional)', ta: 'செய்தி (விருப்பமானது)' },
  'appointment.submit': { en: 'Book Appointment', ta: 'சந்திப்பை பதிவு செய்' },
  'appointment.success': { en: 'Appointment booked successfully!', ta: 'சந்திப்பு வெற்றிகரமாக பதிவு செய்யப்பட்டது!' },

  // Contact
  'contact.title': { en: 'Contact Us', ta: 'எங்களை தொடர்பு கொள்ளுங்கள்' },
  'contact.address': { en: 'Address', ta: 'முகவரி' },
  'contact.phone': { en: 'Phone', ta: 'தொலைபேசி' },
  'contact.emergency': { en: 'Emergency', ta: 'அவசரம்' },
  'contact.email': { en: 'Email', ta: 'மின்னஞ்சல்' },
  'contact.hours': { en: 'Working Hours', ta: 'பணி நேரம்' },
  'contact.hoursValue': { en: '24/7 Emergency Services Available', ta: '24/7 அவசர சேவைகள் கிடைக்கும்' },
  'contact.sendMessage': { en: 'Send Message', ta: 'செய்தி அனுப்பு' },
  'contact.yourName': { en: 'Your Name', ta: 'உங்கள் பெயர்' },
  'contact.yourEmail': { en: 'Your Email', ta: 'உங்கள் மின்னஞ்சல்' },
  'contact.yourMessage': { en: 'Your Message', ta: 'உங்கள் செய்தி' },
  'contact.subtitle': { en: "We're here to help. Reach out to us anytime.", ta: 'உங்களுக்கு உதவ எங்கள் குழு எப்போதும் தயாராக உள்ளது.' },
  'contact.sending': { en: 'Sending...', ta: 'அனுப்புகிறது...' },
  'contact.toast.loginTitle': { en: 'Login Required', ta: 'உள்நுழைவு தேவை' },
  'contact.toast.loginDesc': { en: 'Please log in to send a message.', ta: 'செய்தியை அனுப்ப உள்நுழைக.' },
  'contact.toast.accessTitle': { en: 'Access Denied', ta: 'அணுகல் மறுக்கப்பட்டது' },
  'contact.toast.accessDesc': { en: 'Only patients can send contact messages.', ta: 'தொடர்பு செய்தியை நோயாளிகள் மட்டுமே அனுப்ப முடியும்.' },
  'contact.toast.successTitle': { en: 'Message Sent!', ta: 'செய்தி அனுப்பப்பட்டது!' },
  'contact.toast.successDesc': { en: 'We will get back to you soon.', ta: 'எங்கள் பதில் விரைவில் கிடைக்கும்.' },
  'contact.toast.errorTitle': { en: 'Error', ta: 'பிழை' },
  'contact.toast.errorDesc': { en: 'Failed to send message. Please try again.', ta: 'செய்தியை அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.' },

  // Login
  'login.title': { en: 'Login to Dashboard', ta: 'கட்டுப்பாட்டு பலகையில் உள்நுழை' },
  'login.email': { en: 'Email Address', ta: 'மின்னஞ்சல் முகவரி' },
  'login.password': { en: 'Password', ta: 'கடவுச்சொல்' },
  'login.role': { en: 'Select Your Role', ta: 'உங்கள் பங்கை தேர்வு செய்' },
  'login.admin': { en: 'Admin', ta: 'நிர்வாகி' },
  'login.doctor': { en: 'Doctor', ta: 'மருத்துவர்' },
  'login.nurse': { en: 'Nurse', ta: 'செவிலியர்' },
  'login.patient': { en: 'Patient', ta: 'நோயாளி' },
  'login.submit': { en: 'Sign In', ta: 'உள்நுழை' },
  'login.forgotPassword': { en: 'Forgot Password?', ta: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?' },

  // Dashboard
  'dashboard.overview': { en: 'Dashboard Overview', ta: 'பலகை கண்ணோட்டம்' },
  'dashboard.patients': { en: 'Total Patients', ta: 'மொத்த நோயாளிகள்' },
  'dashboard.doctors': { en: 'Total Doctors', ta: 'மொத்த மருத்துவர்கள்' },
  'dashboard.appointments': { en: 'Appointments Today', ta: 'இன்றைய சந்திப்புகள்' },
  'dashboard.billing': { en: 'Billing Overview', ta: 'கட்டண கண்ணோட்டம்' },
  'dashboard.logout': { en: 'Logout', ta: 'வெளியேறு' },

  // Common
  'common.readMore': { en: 'Read More', ta: 'மேலும் வாசிக்க' },
  'common.close': { en: 'Close', ta: 'மூடு' },
  'common.save': { en: 'Save', ta: 'சேமி' },
  'common.cancel': { en: 'Cancel', ta: 'ரத்து' },
  'common.submit': { en: 'Submit', ta: 'சமர்ப்பி' },
  'common.loading': { en: 'Loading...', ta: 'ஏற்றுகிறது...' },
  'common.confirmationTitle': { en: 'Are you absolutely sure?', ta: 'நீங்கள் முழுமையாக உறுதியாக உள்ளீர்களா?' },
  'common.deleteAccountWarning': { en: 'This action cannot be undone. This will permanently delete your account and remove your data from our servers.', ta: 'இந்த செயலை மீளச் செய்ய முடியாது. இது உங்கள் கணக்கை நிரந்தரமாக நீக்கி, உங்கள் தரவை எங்களது சேவையகங்களில் இருந்து அகற்றும்.' },

  // Patient Profile
  'profile.title': { en: 'Patient Profile', ta: 'நோயாளி சுயவிவரம்' },
  'profile.welcome': { en: 'Welcome back', ta: 'மீண்டும் வருக' },
  'profile.editProfile': { en: 'Edit Profile', ta: 'சுயவிவரத்தை திருத்து' },
  'profile.personalDetails': { en: 'Personal Details', ta: 'தனிப்பட்ட விவரங்கள்' },
  'profile.medicalDetails': { en: 'Medical Details', ta: 'மருத்துவ விவரங்கள்' },
  'profile.appointmentHistory': { en: 'Appointment History', ta: 'சந்திப்பு வரலாறு' },
  'profile.prescriptionHistory': { en: 'Prescription History', ta: 'மருந்து வரலாறு' },
  'profile.fullName': { en: 'Full Name', ta: 'முழு பெயர்' },
  'profile.age': { en: 'Age', ta: 'வயது' },
  'profile.gender': { en: 'Gender', ta: 'பாலினம்' },
  'profile.email': { en: 'Email', ta: 'மின்னஞ்சல்' },
  'profile.phone': { en: 'Phone', ta: 'தொலைபேசி' },
  'profile.address': { en: 'Address', ta: 'முகவரி' },
  'profile.bloodGroup': { en: 'Blood Group', ta: 'இரத்த வகை' },
  'profile.emergencyContact': { en: 'Emergency Contact', ta: 'அவசர தொடர்பு' },
  'profile.allergies': { en: 'Allergies', ta: 'ஒவ்வாமை' },
  'profile.ongoingTreatments': { en: 'Ongoing Treatments', ta: 'தற்போதைய சிகிச்சைகள்' },
  'profile.lastAppointment': { en: 'Last Appointment', ta: 'கடைசி சந்திப்பு' },
  'profile.assignedDoctor': { en: 'Assigned Doctor', ta: 'நியமிக்கப்பட்ட மருத்துவர்' },
  'profile.viewDetails': { en: 'View Details', ta: 'விவரங்களை பார்க்க' },
  'profile.doctorName': { en: 'Doctor', ta: 'மருத்துவர்' },
  'profile.department': { en: 'Department', ta: 'துறை' },
  'profile.date': { en: 'Date', ta: 'தேதி' },
  'profile.time': { en: 'Time', ta: 'நேரம்' },
  'profile.status': { en: 'Status', ta: 'நிலை' },
  'profile.completed': { en: 'Completed', ta: 'முடிந்தது' },
  'profile.upcoming': { en: 'Upcoming', ta: 'வரவிருக்கும்' },
  'profile.cancelled': { en: 'Cancelled', ta: 'ரத்து செய்யப்பட்டது' },
  'profile.medicine': { en: 'Medicine', ta: 'மருந்து' },
  'profile.dosage': { en: 'Dosage', ta: 'அளவு' },
  'profile.duration': { en: 'Duration', ta: 'காலம்' },
  'profile.bloodPressure': { en: 'Blood Pressure', ta: 'இரத்த அழுத்தம்' },
  'profile.sugarLevel': { en: 'Sugar Level', ta: 'சர்க்கரை அளவு' },
  'profile.weight': { en: 'Weight', ta: 'எடை' },
  'profile.height': { en: 'Height', ta: 'உயரம்' },
  'profile.bmi': { en: 'BMI', ta: 'பிஎம்ஐ' },
  'profile.healthTracker': { en: 'Health Tracker', ta: 'சுகாதார கண்காணிப்பு' },
  'profile.noData': { en: 'No data available', ta: 'தரவு இல்லை' },
  'profile.male': { en: 'Male', ta: 'ஆண்' },
  'profile.female': { en: 'Female', ta: 'பெண்' },
  'profile.other': { en: 'Other', ta: 'மற்றவை' },

  // Common / Shared
  'common.noRecords': { en: 'No records', ta: 'பதிவுகள் இல்லை' },
  'common.unknownDate': { en: 'Unknown date', ta: 'தெரியாத தேதி' },
  'common.loadingActivity': { en: 'Loading activity…', ta: 'செயல்பாடு ஏற்றப்படுகிறது…' },
  'common.noRecentActivity': { en: 'No recent activity found.', ta: 'சமீபத்திய செயல்பாடுகள் இல்லை.' },

  // Patient Dashboard
  'patientDashboard.title': { en: 'Patient Dashboard', ta: 'நோயாளி கட்டுப்பாட்டு பலகை' },
  'patientDashboard.subtitle': { en: 'Access your medical records and appointments', ta: 'உங்களின் மருத்துவ பதிவுகள் மற்றும் சந்திப்புகளை அணுகுங்கள்' },
  'patientDashboard.viewProfile': { en: 'View My Profile', ta: 'என் சுயவிவரத்தை பார்க்க' },
  'patientDashboard.stats.upcoming': { en: 'Upcoming Appointments', ta: 'வரவிருக்கும் சந்திப்புகள்' },
  'patientDashboard.stats.prescriptions': { en: 'Prescriptions', ta: 'மருந்து பரிந்துரைகள்' },
  'patientDashboard.stats.pendingBills': { en: 'Pending Bills', ta: 'நிலுவையில் உள்ள கட்டணங்கள்' },
  'patientDashboard.stats.healthRecords': { en: 'Health Records', ta: 'சுகாதார பதிவுகள்' },
  'patientDashboard.stats.bmiLabel': { en: 'BMI', ta: 'உடல் நிறை குறியீடு' },
  'patientDashboard.stats.healthUpdatedPrefix': { en: 'Updated', ta: 'புதுப்பிக்கப்பட்ட தேதி' },
  'patientDashboard.quickActions': { en: 'Quick Actions', ta: 'விரைவு செயல்கள்' },
  'patientDashboard.action.bookAppointment': { en: 'Book New Appointment', ta: 'புதிய சந்திப்பை பதிவு செய்' },
  'patientDashboard.action.updateHealth': { en: 'Update Health Records', ta: 'சுகாதார பதிவுகளை புதுப்பி' },
  'patientDashboard.action.viewDoctors': { en: 'View All Doctors', ta: 'அனைத்து மருத்துவர்களையும் காண' },
  'patientDashboard.recentActivity': { en: 'Recent Activity', ta: 'சமீபத்திய செயல்பாடுகள்' },
  'patientDashboard.activity.defaultTitle': { en: 'Activity update', ta: 'செயல்பாடு புதுப்பிப்பு' },

  // Patient Appointments
  'patientAppointments.title': { en: 'My Appointments', ta: 'என் சந்திப்புகள்' },
  'patientAppointments.subtitle': { en: 'View and manage your medical appointments', ta: 'உங்கள் மருத்துவ சந்திப்புகளை பார்க்கவும் நிர்வகிக்கவும்' },
  'patientAppointments.toggle.showExpired': { en: 'Show Expired', ta: 'காலாவதியானவற்றைக் காண்' },
  'patientAppointments.toggle.showActive': { en: 'Show Active', ta: 'செயலில் உள்ளவற்றைக் காண்' },
  'patientAppointments.bookNew': { en: 'Book New Appointment', ta: 'புதிய சந்திப்பை பதிவு செய்' },
  'patientAppointments.toast.confirmedTitle': { en: 'Appointment Confirmed', ta: 'சந்திப்பு உறுதிப்படுத்தப்பட்டது' },
  'patientAppointments.toast.confirmedWith': { en: 'Your appointment with', ta: 'உங்கள் சந்திப்பு' },
  'patientAppointments.toast.on': { en: 'on', ta: 'நாள்' },
  'patientAppointments.toast.at': { en: 'at', ta: 'நேரத்தில்' },
  'patientAppointments.toast.confirmedSuffix': { en: 'is confirmed.', ta: 'உறுதிப்படுத்தப்பட்டது.' },
  'patientAppointments.reasonLabel': { en: 'Reason for Visit:', ta: 'வருகையின் காரணம்:' },
  'patientAppointments.expiredBadge': { en: 'Expired', ta: 'காலாவதி' },
  'patientAppointments.empty.none': { en: 'No Appointments Found', ta: 'சந்திப்புகள் எதுவும் இல்லை' },
  'patientAppointments.empty.noneDesc': { en: 'No appointments found.', ta: 'எந்த சந்திப்பும் பதிவு செய்யப்படவில்லை.' },
  'patientAppointments.empty.noActive': { en: 'No Active Appointments', ta: 'செயலில் உள்ள சந்திப்புகள் இல்லை' },
  'patientAppointments.empty.noActiveDesc': { en: 'You currently don’t have any upcoming appointments.', ta: 'தற்போது உங்களிடம் வரவிருக்கும் சந்திப்புகள் இல்லை.' },
  'patientAppointments.empty.noExpired': { en: 'No Expired Appointments', ta: 'காலாவதியான சந்திப்புகள் இல்லை' },
  'patientAppointments.empty.noExpiredDesc': { en: 'No expired appointments found.', ta: 'காலாவதியான சந்திப்புகள் எதுவும் இல்லை.' },
  'patientAppointments.empty.bookFirst': { en: 'Book Your First Appointment', ta: 'உங்கள் முதல் சந்திப்பை பதிவு செய்' },
  'patientAppointments.status.pending': { en: 'Pending', ta: 'நிலுவை' },
  'patientAppointments.status.confirmed': { en: 'Confirmed', ta: 'உறுதியானது' },
  'patientAppointments.status.cancelled': { en: 'Cancelled', ta: 'ரத்து செய்யப்பட்டது' },
  'patientAppointments.status.completed': { en: 'Completed', ta: 'முடிந்தது' },
  'patientAppointments.status.expired': { en: 'Expired', ta: 'காலாவதி' },

  // Patient Prescriptions
  'patientPrescriptions.title': { en: 'My Prescriptions', ta: 'என் மருந்து பரிந்துரைகள்' },
  'patientPrescriptions.subtitle': { en: 'View prescriptions issued by your doctors', ta: 'உங்கள் மருத்துவர்கள் வழங்கிய மருந்து பரிந்துரைகளை பார்க்கவும்' },
  'patientPrescriptions.toggle.showExpired': { en: 'Show Expired', ta: 'காலாவதியானவற்றைக் காண்' },
  'patientPrescriptions.toggle.hideExpired': { en: 'Hide Expired', ta: 'காலாவதியானவற்றை மறை' },
  'patientPrescriptions.refresh': { en: 'Refresh', ta: 'புதுப்பி' },
  'patientPrescriptions.cardTitle': { en: 'Prescription', ta: 'மருந்து பரிந்துரை' },
  'patientPrescriptions.doctorPrefix': { en: 'Dr.', ta: 'டாக்டர்' },
  'patientPrescriptions.status.expired': { en: 'Expired', ta: 'காலாவதி' },
  'patientPrescriptions.status.active': { en: 'Active', ta: 'செயலில் உள்ளது' },
  'patientPrescriptions.issued': { en: 'Issued:', ta: 'வெளியிடப்பட்ட தேதி:' },
  'patientPrescriptions.validUntil': { en: 'Valid Until:', ta: 'செல்லுபடியாகும் தேதி:' },
  'patientPrescriptions.diagnosis': { en: 'Diagnosis:', ta: 'நோய்நிலை:' },
  'patientPrescriptions.medications': { en: 'Medications', ta: 'மருந்துகள்' },
  'patientPrescriptions.dosage': { en: 'Dosage:', ta: 'அளவு:' },
  'patientPrescriptions.duration': { en: 'Duration:', ta: 'கால அளவு:' },
  'patientPrescriptions.instructions': { en: 'Instructions:', ta: 'வழிமுறைகள்:' },
  'patientPrescriptions.notes': { en: "Doctor's Notes:", ta: 'மருத்துவரின் குறிப்புகள்:' },
  'patientPrescriptions.empty.title': { en: 'No Prescriptions Found', ta: 'மருந்து பரிந்துரைகள் இல்லை' },
  'patientPrescriptions.empty.descActive': { en: 'You have no active prescriptions.', ta: 'உங்களிடம் செயலில் உள்ள மருந்து பரிந்துரைகள் இல்லை.' },
  'patientPrescriptions.empty.descAll': { en: 'You have no prescriptions yet.', ta: 'உங்களுக்கான எந்த மருந்து பரிந்துரையும் இல்லை.' },

  // Patient Reviews
  'patientReviews.title': { en: 'Rate & Review Doctors', ta: 'மருத்துவர்களை மதிப்பிடவும் கருத்துப்பதியவும்' },
  'patientReviews.subtitle': { en: 'Share your experience with doctors you\'ve visited', ta: 'நீங்கள் சந்தித்த மருத்துவர்களுடன் உங்கள் அனுபவத்தை பகிருங்கள்' },
  'patientReviews.empty.title': { en: 'No Completed Appointments', ta: 'முடிந்த சந்திப்புகள் இல்லை' },
  'patientReviews.empty.desc': { en: "You don't have any completed appointments to review yet. After your appointment is completed, you'll be able to rate and review your doctor here.", ta: 'நீங்கள் மதிப்பிட முடியும் முடிந்த சந்திப்புகள் இதுவரை இல்லை. உங்கள் சந்திப்பு முடிந்தபின், இங்கு மருத்துவரை மதிப்பிடவும் கருத்து பதிவிடவும் முடியும்.' },
  'patientReviews.button.edit': { en: 'Edit Review', ta: 'கருத்தை திருத்து' },
  'patientReviews.button.write': { en: 'Write Review', ta: 'கருத்தை பதிவு செய்' },
  'patientReviews.review.label': { en: 'Your Review', ta: 'உங்கள் கருத்து' },
  'patientReviews.review.badge': { en: 'Reviewed', ta: 'கருத்திடப்பட்டது' },
  'patientReviews.modal.editTitle': { en: 'Edit Your Review', ta: 'உங்கள் கருத்தை திருத்து' },
  'patientReviews.modal.newTitle': { en: 'Write a Review', ta: 'ஒரு கருத்தை பதிவு செய்' },
  'patientReviews.modal.subtitle': { en: 'Share your experience with', ta: 'உங்கள் அனுபவத்தை பகிருங்கள்:' },
  'patientReviews.modal.ratingLabel': { en: 'Rating *', ta: 'மதிப்பீடு *' },
  'patientReviews.modal.reviewLabel': { en: 'Your Review (Optional)', ta: 'உங்கள் கருத்து (விருப்பம்)' },
  'patientReviews.modal.reviewPlaceholder': { en: 'Share details about your experience...', ta: 'உங்கள் அனுபவத்தை விரிவாக பகிருங்கள்...' },
  'patientReviews.modal.updateButton': { en: 'Update Review', ta: 'கருத்தை புதுப்பி' },
  'patientReviews.modal.submitButton': { en: 'Submit Review', ta: 'கருத்தை சமர்ப்பி' },
  'patientReviews.toast.accessDeniedTitle': { en: 'Access denied', ta: 'அணுகல் மறுக்கப்பட்டது' },
  'patientReviews.toast.accessDeniedDesc': { en: 'This page is only available to patients.', ta: 'இந்தப் பக்கம் நோயாளிகளுக்கு மட்டும் கிடைக்கும்.' },
  'patientReviews.toast.invalidRatingTitle': { en: 'Invalid rating', ta: 'தவறான மதிப்பீடு' },
  'patientReviews.toast.invalidRatingDesc': { en: 'Please select a star rating before submitting.', ta: 'சமர்ப்பிக்கும் முன் ஒரு நட்சத்திர மதிப்பீட்டைத் தேர்வு செய்யவும்.' },
  'patientReviews.toast.successNew': { en: 'Review submitted successfully!', ta: 'கருத்து வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!' },
  'patientReviews.toast.successUpdate': { en: 'Review updated successfully!', ta: 'கருத்து வெற்றிகரமாக புதுப்பிக்கப்பட்டது!' },
  'patientReviews.toast.error': { en: 'Failed to submit review. Please try again.', ta: 'கருத்தை சமர்ப்பிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.' },

  // Patient Health Records
  'patientHealth.title': { en: 'Health Records', ta: 'சுகாதார பதிவுகள்' },
  'patientHealth.subtitle': { en: 'Track and manage your health vitals', ta: 'உங்கள் சுகாதார அளவீடுகளை கண்காணித்து நிர்வகிக்கவும்' },
  'patientHealth.button.save': { en: 'Save Changes', ta: 'மாற்றங்களை சேமி' },
  'patientHealth.button.edit': { en: 'Edit Records', ta: 'பதிவுகளை திருத்து' },
  'patientHealth.bmiLabel': { en: 'Body Mass Index (BMI)', ta: 'உடல் நிறை குறியீடு (BMI)' },
  'patientHealth.notSet': { en: 'Not set', ta: 'அமைக்கப்படவில்லை' },
  'patientHealth.placeholder.height': { en: 'Enter height', ta: 'உயரத்தை உள்ளிடவும்' },
  'patientHealth.placeholder.weight': { en: 'Enter weight', ta: 'எடையை உள்ளிடவும்' },
  'patientHealth.placeholder.bloodPressure': { en: 'e.g., 120/80', ta: 'உதாரணம்: 120/80' },
  'patientHealth.placeholder.bloodSugar': { en: 'Enter blood sugar', ta: 'இரத்த சர்க்கரை அளவை உள்ளிடவும்' },
  'patientHealth.placeholder.heartRate': { en: 'Enter heart rate', ta: 'இதய துடிப்பை உள்ளிடவும்' },
  'patientHealth.cards.height': { en: 'Height', ta: 'உயரம்' },
  'patientHealth.cards.weight': { en: 'Weight', ta: 'எடை' },
  'patientHealth.cards.bloodPressure': { en: 'Blood Pressure', ta: 'இரத்த அழுத்தம்' },
  'patientHealth.cards.bloodSugar': { en: 'Blood Sugar', ta: 'இரத்த சர்க்கரை' },
  'patientHealth.cards.heartRate': { en: 'Heart Rate', ta: 'இதய துடிப்பு' },
  'patientHealth.lastUpdated': { en: 'Last updated', ta: 'கடைசியாக புதுப்பிக்கப்பட்ட தேதி' },
  'patientHealth.toast.updatedTitle': { en: 'Health Records Updated', ta: 'சுகாதார பதிவுகள் புதுப்பிக்கப்பட்டது' },
  'patientHealth.toast.updatedDesc': { en: 'Your health information has been saved successfully and synced with your dashboard.', ta: 'உங்கள் சுகாதார தகவல் வெற்றிகரமாக சேமிக்கப்பட்டு பலகையில் பொருந்தியுள்ளது.' },
  'patientHealth.toast.errorTitle': { en: 'Error', ta: 'பிழை' },
  'patientHealth.toast.errorDesc': { en: 'Failed to update health records', ta: 'சுகாதார பதிவுகளைப் புதுப்பிக்க முடியவில்லை' },

  // Patient Billing
  'patientBilling.title': { en: 'My Bills', ta: 'என் கட்டணங்கள்' },
  'patientBilling.subtitle': { en: 'View your medical bills and payment history', ta: 'உங்கள் மருத்துவ கட்டணங்களையும் கட்டண வரலாறையும் பார்க்கவும்' },
  'patientBilling.stats.total': { en: 'Total Bills', ta: 'மொத்த கட்டணங்கள்' },
  'patientBilling.stats.pending': { en: 'Pending', ta: 'நிலுவையில்' },
  'patientBilling.stats.unpaid': { en: 'Unpaid', ta: 'செலுத்தப்படவில்லை' },
  'patientBilling.stats.amountDue': { en: 'Total Amount Due', ta: 'செலுத்த வேண்டிய மொத்த தொகை' },
  'patientBilling.card.allBills': { en: 'All Bills', ta: 'அனைத்து கட்டணங்களும்' },
  'patientBilling.card.description': { en: 'View details and payment status of your medical bills', ta: 'உங்கள் மருத்துவ கட்டணங்களின் விவரங்களையும் கட்டண நிலையையும் பார்க்கவும்' },
  'patientBilling.loading': { en: 'Loading...', ta: 'ஏற்றப்படுகிறது...' },
  'patientBilling.empty': { en: 'No bills found', ta: 'கட்டணங்கள் எதுவும் இல்லை' },
  'patientBilling.status.draft': { en: 'Draft', ta: 'வரைவு' },
  'patientBilling.status.pending': { en: 'Pending', ta: 'நிலுவையில்' },
  'patientBilling.status.finalized': { en: 'Finalized', ta: 'இறுதிப்படுத்தப்பட்டது' },
  'patientBilling.status.paid': { en: 'Paid', ta: 'செலுத்தப்பட்டது' },
  'patientBilling.paymentStatus.unpaid': { en: 'Unpaid', ta: 'செலுத்தப்படவில்லை' },
  'patientBilling.paymentStatus.partial': { en: 'Partial', ta: 'பகுதியளவில்' },
  'patientBilling.paymentStatus.paid': { en: 'Paid', ta: 'செலுத்தப்பட்டது' },
  'patientBilling.details.view': { en: 'View Details', ta: 'விவரங்களை பார்க்க' },
  'patientBilling.details.title': { en: 'Bill Details', ta: 'கட்டண விவரங்கள்' },
  'patientBilling.details.subtitle': { en: 'Detailed breakdown of your medical bill', ta: 'உங்கள் மருத்துவ கட்டணத்தின் விரிவான பகிர்வு' },
  'patientBilling.details.info': { en: 'Bill Information', ta: 'கட்டண தகவல்' },
  'patientBilling.details.consultation': { en: 'Consultation Fee', ta: 'ஆலோசனை கட்டணம்' },
  'patientBilling.details.hospital': { en: 'Hospital Charges', ta: 'மருத்துவமனை கட்டணங்கள்' },
  'patientBilling.details.labTests': { en: 'Lab Tests', ta: 'அறை பரிசோதனைகள்' },
  'patientBilling.details.scans': { en: 'Scans/Imaging', ta: 'ஸ்கேன்/இமேஜிங்' },
  'patientBilling.details.medicines': { en: 'Medicines', ta: 'மருந்துகள்' },
  'patientBilling.details.bedCharges': { en: 'Bed Charges', ta: 'மருத்துவ படுக்கை கட்டணங்கள்' },
  'patientBilling.details.serviceFees': { en: 'Service Fees', ta: 'சேவை கட்டணங்கள்' },
  'patientBilling.details.paymentStatus': { en: 'Payment Status', ta: 'கட்டண நிலை' },
  'patientBilling.details.labSubtotal': { en: 'Lab Tests Subtotal:', ta: 'அறை பரிசோதனைகள் இடைக்கால தொகை:' },
  'patientBilling.details.scanSubtotal': { en: 'Scans Subtotal:', ta: 'ஸ்கேன் இடைக்கால தொகை:' },
  'patientBilling.details.medicineSubtotal': { en: 'Medicines Subtotal:', ta: 'மருந்துகள் இடைக்கால தொகை:' },
  'patientBilling.details.serviceSubtotal': { en: 'Service Fees Subtotal:', ta: 'சேவை கட்டண இடைக்கால தொகை:' },
  'patientBilling.summary.consultation': { en: 'Consultation Fee:', ta: 'ஆலோசனை கட்டணம்:' },
  'patientBilling.summary.hospital': { en: 'Hospital Charges:', ta: 'மருத்துவமனை கட்டணங்கள்:' },
  'patientBilling.summary.grandTotal': { en: 'Grand Total:', ta: 'மொத்த தொகை:' },
  'patientBilling.summary.amountPaid': { en: 'Amount Paid:', ta: 'செலுத்திய தொகை:' },
  'patientBilling.summary.amountDue': { en: 'Amount Due:', ta: 'செலுத்த வேண்டிய தொகை:' },
  'patientBilling.button.download': { en: 'Download PDF', ta: 'PDF ஐ பதிவிறக்கு' },
  'patientBilling.button.close': { en: 'Close', ta: 'மூடு' },
  'patientBilling.toast.comingSoonTitle': { en: 'Coming Soon', ta: 'விரைவில் வருகிறது' },
  'patientBilling.toast.comingSoonDesc': { en: 'PDF download feature will be available soon', ta: 'PDF பதிவிறக்க அம்சம் விரைவில் கிடைக்கும்' },
  'patientBilling.toast.errorTitle': { en: 'Error', ta: 'பிழை' },
  'patientBilling.toast.errorDesc': { en: 'Failed to load bills', ta: 'கட்டணங்களை ஏற்ற முடியவில்லை' },
  'patientBilling.toast.detailsErrorDesc': { en: 'Failed to load bill details', ta: 'கட்டண விவரங்களை ஏற்ற முடியவில்லை' },

  // Dashboard Layout / Settings
  'dashboard.menu.dashboard': { en: 'Dashboard', ta: 'கட்டுப்பாட்டு பலகை' },
  'dashboard.menu.home': { en: 'Home', ta: 'முகப்பு' },
  'dashboard.menu.appointments': { en: 'Appointments', ta: 'சந்திப்புகள்' },
  'dashboard.menu.patients': { en: 'Patients', ta: 'நோயாளிகள்' },
  'dashboard.menu.prescriptions': { en: 'Prescriptions', ta: 'மருந்து பரிந்துரைகள்' },
  'dashboard.menu.reviews': { en: 'Reviews', ta: 'கருத்துகள்' },
  'dashboard.menu.healthRecords': { en: 'Health Records', ta: 'சுகாதார பதிவுகள்' },
  'dashboard.menu.billing': { en: 'Billing', ta: 'கட்டணம்' },
  'dashboard.menu.inventory': { en: 'Inventory', ta: 'சரக்கு' },
  'dashboard.menu.iotDevices': { en: 'IoT Devices', ta: 'IoT சாதனங்கள்' },
  'dashboard.menu.messages': { en: 'Messages', ta: 'செய்திகள்' },
  'dashboard.menu.contactMessages': { en: 'Contact Messages', ta: 'தொடர்பு செய்திகள்' },
  'dashboard.menu.analytics': { en: 'Analytics', ta: 'பகுப்பாய்வு' },
  'dashboard.menu.manageDoctors': { en: 'Manage Doctors', ta: 'மருத்துவர்களை நிர்வகி' },
  'dashboard.menu.manageNurses': { en: 'Manage Nurses', ta: 'செவிலியர்களை நிர்வகி' },
  'dashboard.menu.managePatients': { en: 'Manage Patients', ta: 'நோயாளிகளை நிர்வகி' },
  'dashboard.menu.consultations': { en: 'Consultations', ta: 'ஆலோசனைகள்' },
  'dashboard.menu.settings': { en: 'Settings', ta: 'அமைப்புகள்' },
  'dashboard.menu.viewProfile': { en: 'View Profile', ta: 'சுயவிவரத்தை பார்க்க' },
  'dashboard.menu.editProfile': { en: 'Edit Profile', ta: 'சுயவிவரத்தை திருத்து' },
  'dashboard.menu.changePassword': { en: 'Change Password', ta: 'கடவுச்சொல்லை மாற்று' },
  'dashboard.menu.signOut': { en: 'Sign Out', ta: 'வெளியேறு' },
  'dashboard.menu.deleteAccount': { en: 'Delete Account', ta: 'கணக்கை நீக்கு' },
  'dashboard.menu.deleteConfirm': { en: 'Delete Account', ta: 'கணக்கை நீக்கு' },
  'dashboard.account.admin': { en: 'Admin Account', ta: 'நிர்வாகி கணக்கு' },
  'dashboard.account.doctor': { en: 'Doctor Account', ta: 'மருத்துவர் கணக்கு' },
  'dashboard.account.nurse': { en: 'Nurse Account', ta: 'செவிலியர் கணக்கு' },
  'dashboard.account.patient': { en: 'Patient Account', ta: 'நோயாளி கணக்கு' },
  'dashboard.changePassword.title': { en: 'Change Password', ta: 'கடவுச்சொல்லை மாற்று' },
  'dashboard.changePassword.description': { en: 'Enter your new password below. Password must be at least 8 characters long.', ta: 'உங்கள் புதிய கடவுச்சொல்லை கீழே உள்ளிடவும். கடவுச்சி குறைந்தது 8 எழுத்துகள் கொண்டிருக்க வேண்டும்.' },
  'dashboard.changePassword.newPassword': { en: 'New Password', ta: 'புதிய கடவுச்சொல்' },
  'dashboard.changePassword.confirmPassword': { en: 'Confirm New Password', ta: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்து' },
  'dashboard.changePassword.placeholder': { en: 'Enter new password (min 8 characters)', ta: 'புதிய கடவுச்சொல்லை உள்ளிடவும் (குறைந்தது 8 எழுத்துகள்)' },
  'dashboard.changePassword.placeholderConfirm': { en: 'Confirm new password', ta: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்' },
  'dashboard.changePassword.changing': { en: 'Changing...', ta: 'மாற்றுகிறது...' },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
